language: csharp
mono: none
sudo: required
dist: xenial

addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: latest/beta

script:
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - dotnet build src/BinaryDataReader.sln